### ISSUE TITLE
Verweis auf microStudio Project führt ins Leere

### ISSUE THREAD

**Issue by carlkl** [kantel/microstudio#1]
Der Verweis auf bspw.: [[Python Tutorial 5](https://microstudio.dev/projects/pythontutorial5/code/)](https://microstudio.dev/projects/pythontutorial5/code/) führt leider ins Leere. Auch wenn man mit eigenem account eingeloggt ist.
Ansonsten: Danke für diese Tutorials und den Hinweis auf microStudio. Ich habe schon seit einiger Zeit eine Gaming Engine zum Python lernen als Grundlage für Python Lehrmaterial gesucht! microStudio sieht sehr vielversprechend aus.

**Comment by kantel** [comment]
Oops. danke für den Hinweis. Habe dadurch festgestellt, daß der von mir publizierte Link nur für mich -- also den Inhaber des Accounts -- gülitg ist. Der öffentliche Link ist (im Falle Deines Beispiels) <https://microstudio.dev/i/kantel/pythontutorial5/>. Werde die Links in meinen Beiträgen entsprechend ändern.
